_commit: v1.8.1
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: true
helm: false
homepageEnabled: true
ingClass: nginx-external
ingCname: crt.lol
ingExtraAnnotations: ''
ingHost: dvr.crt.lol
ingName: jellyfin
ingPathType: Prefix
ingWebSockets: true
ingress: true
labels: 'app: jellyfin'
name: jellyfin
namespace: jellyfin
pvc: true
pvcAccessMode: ReadWriteOnce
pvcName: jellyfin
pvcSize: 5Gi
pvcStorageClass: longhorn-retain
reloader: false
resources:
- backups.yaml
- deployments.yaml
- ingresses.yaml
- pvcs.yaml
- services.yaml
service: true
serviceAccount: false
svcName: jellyfin
svcPortName: http
svcPortNum: 8096
svcProtocol: TCP
svcSelector: 'app: jellyfin'
svcTargetPort: http
svcType: ClusterIP
upstreamURL: https://jellyfin.org
url: https://github.com/charlesthomas/homelab-jellyfin
