_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: Media Streamer
homepageEnabled: true
homepageGroup: Media
homepageIcon: jellyfin
homepageName: Jellyfin
ingClass: nginx-external
ingCname: crt.lol
ingExtraAnnotations: ''
ingHost: dvr.crt.lol
ingName: jellyfin
ingPathType: Prefix
ingWebSockets: true
ingress: true
labels: 'app: jellyfin'
name: jellyfin
namespace: jellyfin
pvc: false
reloader: false
resources:
- deployments.yaml
- ingresses.yaml
- services.yaml
service: true
serviceAccount: false
svcName: jellyfin
svcPortName: http
svcPortNum: 8096
svcProtocol: TCP
svcSelector: 'app: jellyfin'
svcTargetPort: http
svcType: ClusterIP
upstreamURL: https://jellyfin.org
url: https://github.com/charlesthomas/homelab-jellyfin
