---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-jellyfin
commonLabels:
  app: jellyfin

resources:
- resources/deployments.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: jellyfin
      namespace: jellyfin
      annotations:
        gethomepage.dev/href: https://dvr.crt.lol
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Media Streamer
        gethomepage.dev/group: Media
        gethomepage.dev/icon: jellyfin
        gethomepage.dev/name: Jellyfin
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
