---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-jellyfin
commonLabels:
  app: jellyfin

resources:
- resources/deployments.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/services.yaml
