---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellyfin-backup-token
  namespace: jellyfin
spec:
  refreshInterval: 1h
  target:
    name: jellyfin-backup-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 274fcdd2-c369-474d-b728-12ff80afc8c6
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scan-token
  namespace: jellyfin
spec:
  target:
    name: scan-token
    deletionPolicy: Delete
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: c7c29fcf-cd4c-4e42-984a-b09a5a1157ef
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
