---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/jellyfin-backup: enabled
    recurring-job.longhorn.io/jellyfin-snapshot: enabled

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-retain
  volumeMode: Filesystem
